apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-dummy
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/himanshunigam-456/welcomemyshow-gitops.git
    targetRevision: main
    path: clusters/prod/workloads/platform-dummy

  destination:
    server: https://kubernetes.default.svc
    namespace: platform

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

